// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj2H9DUGfrrSf7gt2iS__sR6XUJB8_jIw',
    appId: '1:617461586870:web:9722e23961a7dbb73dff17',
    messagingSenderId: '617461586870',
    projectId: 'minimal-social-app-7ba55',
    authDomain: 'minimal-social-app-7ba55.firebaseapp.com',
    storageBucket: 'minimal-social-app-7ba55.appspot.com',
    measurementId: 'G-04M80KQB4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDP_ks3WzGAeE0-LahG9nhefCNASyvLd0',
    appId: '1:617461586870:android:1bc49a89ac34863a3dff17',
    messagingSenderId: '617461586870',
    projectId: 'minimal-social-app-7ba55',
    storageBucket: 'minimal-social-app-7ba55.appspot.com',
  );
}
